"""
Stock Universe - All NSE Listed Stocks
======================================
Contains comprehensive list of NSE listed stocks organized by category.
"""

# Nifty 50 Stocks
NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "SBIN", "BHARTIARTL",
    "ITC", "KOTAKBANK", "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN", "SUNPHARMA",
    "BAJFINANCE", "WIPRO", "HCLTECH", "TATAMOTORS", "TATASTEEL", "ADANIENT", "POWERGRID",
    "NTPC", "ONGC", "ULTRACEMCO", "JSWSTEEL", "BAJAJFINSV", "TECHM", "INDUSINDBK",
    "NESTLEIND", "GRASIM", "HDFCLIFE", "DRREDDY", "COALINDIA", "SBILIFE", "CIPLA",
    "BRITANNIA", "EICHERMOT", "APOLLOHOSP", "DIVISLAB", "BPCL", "TATACONSUM",
    "HEROMOTOCO", "M&M", "ADANIPORTS", "HINDALCO", "BAJAJ-AUTO", "SHRIRAMFIN", "LTIM",
]

# Nifty Next 50
NIFTY_NEXT_50 = [
    "ABB", "ADANIGREEN", "AMBUJACEM", "ATGL", "AUROPHARMA", "BANDHANBNK", "BANKBARODA",
    "BERGEPAINT", "BIOCON", "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR", "DLF",
    "DABUR", "GAIL", "GODREJCP", "HAVELLS", "ICICIPRULI", "IGL", "INDUSTOWER", "IOC",
    "IRCTC", "JINDALSTEL", "JUBLFOOD", "LUPIN", "MARICO", "MCDOWELL-N", "MOTHERSON",
    "MUTHOOTFIN", "NAUKRI", "NHPC", "NMDC", "OBEROIRLTY", "OFSS", "PAGEIND", "PAYTM",
    "PGHH", "PIDILITIND", "PNB", "POLICYBZR", "POLYCAB", "SAIL", "SBICARD", "SRF",
    "SIEMENS", "TATAPOWER", "TORNTPHARM", "TRENT", "UPL", "VBL", "VEDL", "YESBANK", "ZOMATO",
]

# Nifty Midcap 100
NIFTY_MIDCAP_100 = [
    "ABCAPITAL", "ACC", "ALKEM", "ASHOKLEY", "ASTRAL", "ATUL", "AUBANK", "BALKRISIND", "BEL",
    "BHEL", "CANFINHOME", "CGPOWER", "COROMANDEL", "CUMMINSIND", "DALBHARAT", "DEEPAKNTR",
    "DIXON", "ESCORTS", "EXIDEIND", "FEDERALBNK", "FSL", "GLENMARK", "GMRINFRA", "GNFC",
    "GUJGASLTD", "HAL", "HONAUT", "IDFCFIRSTB", "IIFL", "INDHOTEL", "IRFC", "ISEC",
    "JKCEMENT", "JSL", "JUBLINGREA", "KAJARIACER", "KPITTECH", "L&TFH", "LALPATHLAB",
    "LAURUSLABS", "LICHSGFIN", "LTTS", "MANAPPURAM", "MFSL", "MINDTREE", "MPHASIS",
    "MRF", "NAM-INDIA", "NATIONALUM", "NAVINFLUOR", "PERSISTENT", "PETRONET", "PFC",
    "PIIND", "PVR", "RAMCOCEM", "RECLTD", "SJVN", "SOLARINDS", "SUNTV", "SUPREMEIND",
    "SYNGENE", "TATACHEM", "TATACOMM", "TATAELXSI", "THERMAX", "TIINDIA", "TORNTPOWER",
    "TVSMOTOR", "UBL", "UNIONBANK", "VOLTAS", "WHIRLPOOL", "ZEEL", "ZYDUSLIFE",
    "AFFLE", "AJANTPHARM", "AMARAJABAT", "APLAPOLLO", "BATAINDIA", "BHARATFORG",
    "BLUESTARCO", "CROMPTON", "CYIENT", "EMAMILTD", "FLUOROCHEM", "FORTIS", "GRINDWELL",
    "GSPL", "HAPPSTMNDS", "HINDPETRO", "INDIAMART", "INTELLECT", "IPCALAB", "JBCHEPHARM",
    "JSWENERGY", "JUSTDIAL", "KEI", "KIMS", "LATENTVIEW", "MAPMYINDIA", "MAXHEALTH",
    "MCX", "MEDANTA", "METROPOLIS", "ROUTE", "RVNL", "SAFARI", "SCHAEFFLER", "SONACOMS",
    "SUNDARMFIN", "SYMPHONY", "TANLA", "TIMKEN", "TRIDENT", "UTIAMC", "VGUARD",
]

# Nifty Smallcap 100
NIFTY_SMALLCAP_100 = [
    "AARTIIND", "ADANIPOWER", "ALKYLAMINE", "ANGELONE", "ANURAS", "ASTRAZEN", "AVANTIFEED",
    "BAJAJHLDNG", "BALRAMCHIN", "BAYERCROP", "BEML", "BIRLACORPN", "BSOFT", "CARBORUNIV",
    "CASTROLIND", "CDSL", "CENTURYTEX", "CESC", "CHAMBLFERT", "COCHINSHIP", "COFORGE",
    "CUB", "DCMSHRIRAM", "DHANUKA", "ECLERX", "EDELWEISS", "ENGINERSIN", "EQUITAS",
    "FACT", "FINCABLES", "GARFIBRES", "GLAXO", "GOCOLORS", "GODFRYPHLP", "GRAPHITE",
    "GSFC", "GUJALKALI", "HCG", "HFCL", "HGS", "HINDCOPPER", "HINDZINC", "HUDCO",
    "ICICIGI", "IDBI", "IDEA", "IEX", "INDIACEM", "INFIBEAM", "IOB", "ISGEC",
    "ITDC", "ITI", "J&KBANK", "JAMNAAUTO", "JBMA", "JKLAKSHMI", "JKPAPER", "JMFINANCIL",
    "KALYANKJIL", "KANSAINER", "KEC", "KIOCL", "KNRCON", "KPRMILL", "KSB", "LEMONTREE",
    "LINDEINDIA", "LUXIND", "MAHINDCIE", "MAHLOG", "MAHSEAMLES", "MAITHANALL", "MARKSANS",
    "MASTEK", "MAZAGON", "MIDHANI", "MMTC", "MOIL", "MSTCLTD", "NESCO", "NETWORK18",
    "NFL", "NLCINDIA", "NOCIL", "NUCLEUS", "OLECTRA", "ORIENTELEC", "PARAGMILK", "PATELENG",
    "PCBL", "PFIZER", "PHOENIXLTD", "POWERINDIA", "PRAJIND", "PRSMJOHNSN", "QUESS",
    "RADICO", "RAIN", "RAJESHEXPO", "RALLIS", "RATNAMANI", "RAYMOND", "RBLBANK", "RCF",
    "REDINGTON", "RELIGARE", "RITES", "SARDAEN", "SCHNEIDER", "SEQUENT", "SHILPAMED",
    "SHREECEM", "SHYAMMETL", "SOBHA", "SOUTHBANK", "SPARC", "STAR", "STARCEMENT",
    "SUBROS", "SUMICHEM", "SUNFLAG", "SUPRAJIT", "SURYAROSNI", "SUZLON", "SWANENERGY",
    "TATAINVEST", "TATAMETALI", "TCI", "TCNSBRANDS", "TEAMLEASE", "TCIEXP", "TECHNO",
    "TEXRAIL", "TITAN", "TMB", "TORNTPOWER", "TRITURBINE", "TV18BRDCST", "TVTODAY",
    "UCOBANK", "UFLEX", "UJJIVAN", "UJJIVANSFB", "VAIBHAVGBL", "VARROC", "VINATIORGA",
    "VIPIND", "VMART", "VOLTAMP", "VSTIND", "WELCORP", "WELSPUNIND", "WESTLIFE",
    "WOCKPHARMA", "XPROINDIA", "YATRA", "ZENSARTECH", "ZODIACJRD",
]

# Additional popular stocks not in above indices
ADDITIONAL_STOCKS = [
    "AARTIDRUGS", "AAVAS", "ABFRL", "ABSLAMC", "ACCELYA", "ACE", "ADVENZYMES",
    "AEGISCHEM", "AFFLE", "AGARIND", "AGROPHOS", "AHLUCONT", "AIAENG", "AIRAN",
    "AJMERA", "AKZOINDIA", "ALEMBICLTD", "ALEXCON", "ALLCARGO", "AMBIKCO", "AMIORG",
    "ANANTRAJ", "ANDHRAPER", "ANDHRAPAP", "ANDREWYU", "ANUP", "APARINDS", "APCOTEX",
    "APEX", "APLLTD", "APTECHT", "APTUS", "ARCHIDPLY", "ARIHANTCAP", "ARIHANTSUP",
    "ARMANFIN", "ARTO", "ARVINDFASN", "ARVIND", "ASAHISONG", "ASHAPURMIN", "ASHIANA",
    "ASKAUTOLTD", "ASTRAMICRO", "ASTRAZEN", "ATFL", "ATLANTA", "AURIONPRO", "AUTOAXLES",
    "AVADHSUGAR", "AVANTI", "AXISCADES", "AYMSYNTEX", "BANARISUG", "BANCOINDIA",
    "BASF", "BBOX", "BBTC", "BCG", "BDL", "BEPL", "BFUTILITIE", "BHAGERIA",
    "BHARATGEAR", "BHARATWIRE", "BIGBLOC", "BIL", "BINDALAGRO", "BIOFILCHEM",
    "BLISSGVS", "BLKASHYAP", "BLS", "BODALCHEM", "BOROLTD", "BORORENEW", "BPCL",
    "BPML", "BRANDHOUSE", "BSE", "BURNPUR", "BUTTERFLY", "CALSOFT", "CAMLINFINE",
    "CAMPUS", "CANDC", "CANTABIL", "CAPLIPOINT", "CARYSIL", "CCL", "CEATLTD",
    "CENTRALBK", "CENTRUM", "CENTURYPLY", "CERA", "CHALET", "CHEMCON", "CHEMFAB",
    "CHENNPETRO", "CHKPLASTFOOD", "CHOICEIN", "CIGNITITEC", "CINELINE", "CINEVISTA",
    "CLEAN", "CMSINFO", "COASTCORP", "COMPINFO", "CONCORDBIO", "CONFIPET",
    "CONTROLPR", "CORALFINAC", "COSMOFIRST", "CRAFTSMAN", "CREST", "CRISIL",
]

# Commodities/Indices for tracking
COMMODITIES = {
    "GOLD": "GC=F",      # Gold Futures
    "SILVER": "SI=F",    # Silver Futures
    "CRUDE_OIL": "CL=F", # Crude Oil Futures
    "NATURAL_GAS": "NG=F", # Natural Gas
    "COPPER": "HG=F",    # Copper Futures
}

# Global Indices
GLOBAL_INDICES = {
    "DOW_JONES": "^DJI",
    "S&P_500": "^GSPC",
    "NASDAQ": "^IXIC",
    "FTSE_100": "^FTSE",
    "DAX": "^GDAXI",
    "NIKKEI_225": "^N225",
    "HANG_SENG": "^HSI",
    "SHANGHAI": "000001.SS",
}

# Create combined lists
NIFTY_100 = NIFTY_50 + NIFTY_NEXT_50
NIFTY_200 = NIFTY_100 + NIFTY_MIDCAP_100[:100]
NIFTY_500 = NIFTY_200 + NIFTY_SMALLCAP_100 + ADDITIONAL_STOCKS[:200]

# Full universe - remove duplicates
ALL_STOCKS = list(set(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_100 + NIFTY_SMALLCAP_100 + ADDITIONAL_STOCKS))
ALL_STOCKS.sort()

# Quick access organized list
STOCKS_BY_CATEGORY = {
    "Nifty 50": NIFTY_50,
    "Nifty Next 50": NIFTY_NEXT_50,
    "Nifty Midcap 100": NIFTY_MIDCAP_100,
    "Nifty Smallcap 100": NIFTY_SMALLCAP_100,
    "All Stocks": ALL_STOCKS,
}

def get_all_stocks_sorted():
    """Get all stocks sorted alphabetically."""
    return sorted(ALL_STOCKS)

def parse_custom_symbols(text: str) -> list:
    """Parse custom comma/space/newline separated symbols."""
    # Replace various separators with comma
    text = text.replace('\n', ',').replace('\t', ',').replace(';', ',').replace(' ', ',')
    # Split and clean
    symbols = [s.strip().upper() for s in text.split(',') if s.strip()]
    # Remove duplicates while preserving order
    seen = set()
    unique = []
    for s in symbols:
        if s not in seen:
            seen.add(s)
            unique.append(s)
    return unique
